version: '3.8'

services:
  ytip-backend:
    build: ./backend
    container_name: ytip-backend
    restart: unless-stopped
    ports:
      - "8001:8001"
    env_file:
      - .env
    networks:
      - ytip-network

  ytip-frontend:
    build: ./web
    container_name: ytip-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://ytip-backend:8001
    depends_on:
      - ytip-backend
    networks:
      - ytip-network

networks:
  ytip-network:
    driver: bridge
