"""
Chunk 4 content sources — specialty coffee publications, communities,
Instagram accounts, research organizations, and blogs.

This file is a staging area. The CONTENT_SOURCES list gets imported by
the chunk-4 implementation to seed the content_sources table.
"""

CONTENT_SOURCES = [
    # ------------------------------------------------------------------
    # PUBLICATIONS (20+)
    # ------------------------------------------------------------------
    {
        "source_type": "publication",
        "name": "Sprudge",
        "city": None,
        "country": "USA",
        "tier": None,
        "website_url": "https://sprudge.com",
        "rss_url": "https://sprudge.com/feed",
        "instagram_handle": "sprudge",
        "relevance_tags": ["coffee_news", "specialty_coffee", "industry", "reviews"],
        "scrape_frequency": "daily",
    },
    {
        "source_type": "publication",
        "name": "Perfect Daily Grind",
        "city": None,
        "country": "UK",
        "tier": None,
        "website_url": "https://perfectdailygrind.com",
        "rss_url": "https://perfectdailygrind.com/feed",
        "instagram_handle": "perfectdailygrind",
        "relevance_tags": ["coffee_news", "specialty_coffee", "origin", "education"],
        "scrape_frequency": "daily",
    },
    {
        "source_type": "publication",
        "name": "Barista Magazine",
        "city": None,
        "country": "USA",
        "tier": None,
        "website_url": "https://baristamagazine.com",
        "rss_url": "https://baristamagazine.com/feed",
        "instagram_handle": "baristamagazine",
        "relevance_tags": ["barista", "specialty_coffee", "competition", "industry"],
        "scrape_frequency": "daily",
    },
    {
        "source_type": "publication",
        "name": "Roast Magazine",
        "city": None,
        "country": "USA",
        "tier": None,
        "website_url": "https://roastmagazine.com",
        "rss_url": "https://roastmagazine.com/feed",
        "instagram_handle": "roastmagazine",
        "relevance_tags": ["roasting", "specialty_coffee", "origin", "business"],
        "scrape_frequency": "daily",
    },
    {
        "source_type": "publication",
        "name": "European Coffee Trip",
        "city": "Prague",
        "country": "Czech Republic",
        "tier": None,
        "website_url": "https://europeancoffeetrip.com",
        "rss_url": "https://europeancoffeetrip.com/feed",
        "instagram_handle": "europeancoffeetrip",
        "relevance_tags": ["cafe_reviews", "specialty_coffee", "travel", "europe"],
        "scrape_frequency": "daily",
    },
    {
        "source_type": "publication",
        "name": "Daily Coffee News",
        "city": None,
        "country": "USA",
        "tier": None,
        "website_url": "https://dailycoffeenews.com",
        "rss_url": "https://dailycoffeenews.com/feed",
        "instagram_handle": "dailycoffeenews",
        "relevance_tags": ["coffee_news", "industry", "business", "specialty_coffee"],
        "scrape_frequency": "daily",
    },
    {
        "source_type": "publication",
        "name": "Fresh Cup Magazine",
        "city": None,
        "country": "USA",
        "tier": None,
        "website_url": "https://freshcup.com",
        "rss_url": "https://freshcup.com/feed",
        "instagram_handle": "freshcupmagazine",
        "relevance_tags": ["coffee_news", "tea", "specialty_coffee", "business"],
        "scrape_frequency": "daily",
    },
    {
        "source_type": "publication",
        "name": "Standart Magazine",
        "city": "Bratislava",
        "country": "Slovakia",
        "tier": None,
        "website_url": "https://standartmag.com",
        "rss_url": None,
        "instagram_handle": "standartmag",
        "relevance_tags": ["specialty_coffee", "culture", "design", "long_form"],
        "scrape_frequency": "monthly",
    },
    {
        "source_type": "publication",
        "name": "Drift Magazine",
        "city": None,
        "country": "USA",
        "tier": None,
        "website_url": "https://driftmag.com",
        "rss_url": None,
        "instagram_handle": "driftmag",
        "relevance_tags": ["coffee_culture", "city_guides", "long_form", "photography"],
        "scrape_frequency": "monthly",
    },
    {
        "source_type": "publication",
        "name": "25 Magazine (SCA)",
        "city": None,
        "country": "USA",
        "tier": None,
        "website_url": "https://sca.coffee/25-magazine",
        "rss_url": None,
        "instagram_handle": "specialtycoffeeassoc",
        "relevance_tags": ["specialty_coffee", "research", "industry", "standards"],
        "scrape_frequency": "monthly",
    },
    {
        "source_type": "publication",
        "name": "CoffeeBI (Coffee Business Intelligence)",
        "city": None,
        "country": "Italy",
        "tier": None,
        "website_url": "https://coffeebi.com",
        "rss_url": "https://coffeebi.com/feed",
        "instagram_handle": "coffeebi",
        "relevance_tags": ["market_data", "business_intelligence", "industry", "trends"],
        "scrape_frequency": "weekly",
    },
    {
        "source_type": "publication",
        "name": "World Coffee Portal",
        "city": "London",
        "country": "UK",
        "tier": None,
        "website_url": "https://worldcoffeeportal.com",
        "rss_url": "https://worldcoffeeportal.com/feed",
        "instagram_handle": "worldcoffeeportal",
        "relevance_tags": ["market_data", "industry", "cafe_chains", "business"],
        "scrape_frequency": "weekly",
    },
    {
        "source_type": "publication",
        "name": "Coffee Intelligence",
        "city": "London",
        "country": "UK",
        "tier": None,
        "website_url": "https://coffeeintelligence.com",
        "rss_url": "https://coffeeintelligence.com/feed",
        "instagram_handle": None,
        "relevance_tags": ["market_data", "consumer_trends", "industry", "research"],
        "scrape_frequency": "weekly",
    },
    {
        "source_type": "publication",
        "name": "Comunicaffe",
        "city": "Milan",
        "country": "Italy",
        "tier": None,
        "website_url": "https://comunicaffe.com",
        "rss_url": "https://comunicaffe.com/feed",
        "instagram_handle": "comunicaffe",
        "relevance_tags": ["coffee_news", "espresso", "italy", "industry"],
        "scrape_frequency": "daily",
    },
    {
        "source_type": "publication",
        "name": "Global Coffee Report",
        "city": None,
        "country": "Australia",
        "tier": None,
        "website_url": "https://gcrmag.com",
        "rss_url": "https://gcrmag.com/feed",
        "instagram_handle": "globalcoffeereport",
        "relevance_tags": ["coffee_news", "industry", "supply_chain", "business"],
        "scrape_frequency": "weekly",
    },
    {
        "source_type": "publication",
        "name": "BeanScene Magazine",
        "city": "Melbourne",
        "country": "Australia",
        "tier": None,
        "website_url": "https://beanscenecoffee.com",
        "rss_url": "https://beanscenecoffee.com/feed",
        "instagram_handle": "beanscenemagazine",
        "relevance_tags": ["coffee_news", "specialty_coffee", "australia", "cafe"],
        "scrape_frequency": "weekly",
    },
    {
        "source_type": "publication",
        "name": "Caffeine Magazine",
        "city": "London",
        "country": "UK",
        "tier": None,
        "website_url": "https://caffeinemag.com",
        "rss_url": "https://caffeinemag.com/feed",
        "instagram_handle": "caffeinemag",
        "relevance_tags": ["coffee_culture", "specialty_coffee", "uk", "reviews"],
        "scrape_frequency": "weekly",
    },
    {
        "source_type": "publication",
        "name": "Coffee t&i Magazine",
        "city": None,
        "country": "Germany",
        "tier": None,
        "website_url": "https://coffee-ti.com",
        "rss_url": None,
        "instagram_handle": "coffeetandi",
        "relevance_tags": ["coffee_news", "industry", "europe", "trade"],
        "scrape_frequency": "weekly",
    },
    {
        "source_type": "publication",
        "name": "The Coffee Compass",
        "city": None,
        "country": "USA",
        "tier": None,
        "website_url": "https://thecoffeecompass.com",
        "rss_url": "https://thecoffeecompass.com/feed",
        "instagram_handle": "thecoffeecompass",
        "relevance_tags": ["reviews", "specialty_coffee", "roasters", "education"],
        "scrape_frequency": "weekly",
    },
    {
        "source_type": "publication",
        "name": "Specialty Coffee Chronicle",
        "city": None,
        "country": "USA",
        "tier": None,
        "website_url": "https://scaa.org/chronicle",
        "rss_url": None,
        "instagram_handle": None,
        "relevance_tags": ["specialty_coffee", "research", "education", "industry"],
        "scrape_frequency": "monthly",
    },
    # ------------------------------------------------------------------
    # REDDIT COMMUNITIES (11)
    # ------------------------------------------------------------------
    {
        "source_type": "reddit",
        "name": "r/coffee",
        "city": None,
        "country": None,
        "tier": None,
        "reddit_subreddit": "coffee",
        "website_url": "https://reddit.com/r/coffee",
        "relevance_tags": ["community", "coffee", "reviews", "equipment"],
        "scrape_frequency": "daily",
    },
    {
        "source_type": "reddit",
        "name": "r/espresso",
        "city": None,
        "country": None,
        "tier": None,
        "reddit_subreddit": "espresso",
        "website_url": "https://reddit.com/r/espresso",
        "relevance_tags": ["community", "espresso", "equipment", "dialing_in"],
        "scrape_frequency": "daily",
    },
    {
        "source_type": "reddit",
        "name": "r/roasting",
        "city": None,
        "country": None,
        "tier": None,
        "reddit_subreddit": "roasting",
        "website_url": "https://reddit.com/r/roasting",
        "relevance_tags": ["community", "roasting", "home_roasting", "profiles"],
        "scrape_frequency": "daily",
    },
    {
        "source_type": "reddit",
        "name": "r/cafe",
        "city": None,
        "country": None,
        "tier": None,
        "reddit_subreddit": "cafe",
        "website_url": "https://reddit.com/r/cafe",
        "relevance_tags": ["community", "cafe", "atmosphere", "recommendations"],
        "scrape_frequency": "daily",
    },
    {
        "source_type": "reddit",
        "name": "r/pourover",
        "city": None,
        "country": None,
        "tier": None,
        "reddit_subreddit": "pourover",
        "website_url": "https://reddit.com/r/pourover",
        "relevance_tags": ["community", "pour_over", "brew_methods", "specialty_coffee"],
        "scrape_frequency": "daily",
    },
    {
        "source_type": "reddit",
        "name": "r/JamesHoffmann",
        "city": None,
        "country": None,
        "tier": None,
        "reddit_subreddit": "JamesHoffmann",
        "website_url": "https://reddit.com/r/JamesHoffmann",
        "relevance_tags": ["community", "coffee_education", "influencer", "specialty_coffee"],
        "scrape_frequency": "weekly",
    },
    {
        "source_type": "reddit",
        "name": "r/CoffeeGoneWild",
        "city": None,
        "country": None,
        "tier": None,
        "reddit_subreddit": "CoffeeGoneWild",
        "website_url": "https://reddit.com/r/CoffeeGoneWild",
        "relevance_tags": ["community", "coffee", "fun", "latte_art"],
        "scrape_frequency": "weekly",
    },
    {
        "source_type": "reddit",
        "name": "r/specialtycoffee",
        "city": None,
        "country": None,
        "tier": None,
        "reddit_subreddit": "specialtycoffee",
        "website_url": "https://reddit.com/r/specialtycoffee",
        "relevance_tags": ["community", "specialty_coffee", "origin", "tasting_notes"],
        "scrape_frequency": "daily",
    },
    {
        "source_type": "reddit",
        "name": "r/india (food posts)",
        "city": None,
        "country": "India",
        "tier": None,
        "reddit_subreddit": "india",
        "website_url": "https://reddit.com/r/india",
        "relevance_tags": ["community", "india", "food", "cafe_culture"],
        "scrape_frequency": "weekly",
    },
    {
        "source_type": "reddit",
        "name": "r/barista",
        "city": None,
        "country": None,
        "tier": None,
        "reddit_subreddit": "barista",
        "website_url": "https://reddit.com/r/barista",
        "relevance_tags": ["community", "barista", "latte_art", "cafe_work"],
        "scrape_frequency": "daily",
    },
    {
        "source_type": "reddit",
        "name": "r/latte_art",
        "city": None,
        "country": None,
        "tier": None,
        "reddit_subreddit": "latte_art",
        "website_url": "https://reddit.com/r/latte_art",
        "relevance_tags": ["community", "latte_art", "barista", "espresso"],
        "scrape_frequency": "weekly",
    },
    # ------------------------------------------------------------------
    # INSTAGRAM ACCOUNTS (25)
    # ------------------------------------------------------------------
    # Global coffee influencers
    {
        "source_type": "instagram",
        "name": "James Hoffmann",
        "city": "London",
        "country": "UK",
        "tier": None,
        "instagram_handle": "jimseven",
        "website_url": "https://www.jameshoffmann.co.uk",
        "relevance_tags": ["coffee_influencer", "education", "reviews", "specialty_coffee"],
        "scrape_frequency": "weekly",
    },
    {
        "source_type": "instagram",
        "name": "Lance Hedrick",
        "city": None,
        "country": "USA",
        "tier": None,
        "instagram_handle": "lance.hedrick",
        "website_url": "https://www.youtube.com/@LanceHedrick",
        "relevance_tags": ["coffee_influencer", "espresso", "education", "equipment"],
        "scrape_frequency": "weekly",
    },
    {
        "source_type": "instagram",
        "name": "Morgan Eckroth",
        "city": None,
        "country": "USA",
        "tier": None,
        "instagram_handle": "morgandrinkscoffee",
        "website_url": "https://www.youtube.com/@morgandrinkscoffee",
        "relevance_tags": ["coffee_influencer", "barista_champion", "education", "specialty_coffee"],
        "scrape_frequency": "weekly",
    },
    {
        "source_type": "instagram",
        "name": "Kyle Ramage",
        "city": None,
        "country": "USA",
        "tier": None,
        "instagram_handle": "kyleramage",
        "website_url": None,
        "relevance_tags": ["coffee_influencer", "barista", "competition", "specialty_coffee"],
        "scrape_frequency": "weekly",
    },
    {
        "source_type": "instagram",
        "name": "Patrik Rolf",
        "city": "Stockholm",
        "country": "Sweden",
        "tier": None,
        "instagram_handle": "patrikrolf",
        "website_url": "https://www.patrikrolf.com",
        "relevance_tags": ["coffee_influencer", "specialty_coffee", "roasting", "education"],
        "scrape_frequency": "weekly",
    },
    {
        "source_type": "instagram",
        "name": "European Coffee Trip",
        "city": "Prague",
        "country": "Czech Republic",
        "tier": None,
        "instagram_handle": "europeancoffeetrip",
        "website_url": "https://europeancoffeetrip.com",
        "relevance_tags": ["cafe_reviews", "specialty_coffee", "travel", "europe"],
        "scrape_frequency": "weekly",
    },
    {
        "source_type": "instagram",
        "name": "The Real Sprometheus",
        "city": None,
        "country": "USA",
        "tier": None,
        "instagram_handle": "the_real_sprometheus",
        "website_url": "https://www.youtube.com/@Sprometheus",
        "relevance_tags": ["coffee_influencer", "espresso", "equipment_reviews", "specialty_coffee"],
        "scrape_frequency": "weekly",
    },
    # Indian food and coffee accounts
    {
        "source_type": "instagram",
        "name": "Delhi Food Guide",
        "city": "Delhi",
        "country": "India",
        "tier": None,
        "instagram_handle": "delhifoodguide",
        "website_url": None,
        "relevance_tags": ["india", "food", "cafe", "delhi", "reviews"],
        "scrape_frequency": "weekly",
    },
    {
        "source_type": "instagram",
        "name": "Mumbai Foodies",
        "city": "Mumbai",
        "country": "India",
        "tier": None,
        "instagram_handle": "mumbaifoodies",
        "website_url": None,
        "relevance_tags": ["india", "food", "cafe", "mumbai", "reviews"],
        "scrape_frequency": "weekly",
    },
    {
        "source_type": "instagram",
        "name": "Bangalore Food Guide",
        "city": "Bangalore",
        "country": "India",
        "tier": None,
        "instagram_handle": "bangalorefoodguide",
        "website_url": None,
        "relevance_tags": ["india", "food", "cafe", "bangalore", "reviews"],
        "scrape_frequency": "weekly",
    },
    {
        "source_type": "instagram",
        "name": "Kolkata Foodies Official",
        "city": "Kolkata",
        "country": "India",
        "tier": None,
        "instagram_handle": "kolkatafoodiesofficial",
        "website_url": None,
        "relevance_tags": ["india", "food", "cafe", "kolkata", "reviews"],
        "scrape_frequency": "weekly",
    },
    {
        "source_type": "instagram",
        "name": "Chennai Food Guide",
        "city": "Chennai",
        "country": "India",
        "tier": None,
        "instagram_handle": "chennaifoodguide",
        "website_url": None,
        "relevance_tags": ["india", "food", "cafe", "chennai", "reviews"],
        "scrape_frequency": "weekly",
    },
    {
        "source_type": "instagram",
        "name": "Pune Foodies Club",
        "city": "Pune",
        "country": "India",
        "tier": None,
        "instagram_handle": "punefoodiesclub",
        "website_url": None,
        "relevance_tags": ["india", "food", "cafe", "pune", "reviews"],
        "scrape_frequency": "weekly",
    },
    {
        "source_type": "instagram",
        "name": "India Eats",
        "city": None,
        "country": "India",
        "tier": None,
        "instagram_handle": "indiaeats",
        "website_url": None,
        "relevance_tags": ["india", "food", "cafe", "travel", "reviews"],
        "scrape_frequency": "weekly",
    },
    {
        "source_type": "instagram",
        "name": "Feed Your Wanderlust",
        "city": None,
        "country": "India",
        "tier": None,
        "instagram_handle": "feedyourwanderlust",
        "website_url": None,
        "relevance_tags": ["india", "food", "travel", "cafe", "reviews"],
        "scrape_frequency": "weekly",
    },
    {
        "source_type": "instagram",
        "name": "Indian Coffee Community",
        "city": None,
        "country": "India",
        "tier": None,
        "instagram_handle": "indiancoffeecommunity",
        "website_url": None,
        "relevance_tags": ["india", "specialty_coffee", "community", "cafe"],
        "scrape_frequency": "weekly",
    },
    {
        "source_type": "instagram",
        "name": "The Coffee Brigade",
        "city": None,
        "country": "India",
        "tier": None,
        "instagram_handle": "thecoffeebrigade",
        "website_url": None,
        "relevance_tags": ["india", "specialty_coffee", "community", "education"],
        "scrape_frequency": "weekly",
    },
    # Kolkata-specific accounts
    {
        "source_type": "instagram",
        "name": "Kolkata Foodie",
        "city": "Kolkata",
        "country": "India",
        "tier": None,
        "instagram_handle": "kolkatafoodie",
        "website_url": None,
        "relevance_tags": ["kolkata", "food", "cafe", "reviews", "local"],
        "scrape_frequency": "weekly",
    },
    {
        "source_type": "instagram",
        "name": "Kolkata Food Diaries",
        "city": "Kolkata",
        "country": "India",
        "tier": None,
        "instagram_handle": "kolkata_food_diaries",
        "website_url": None,
        "relevance_tags": ["kolkata", "food", "cafe", "reviews", "local"],
        "scrape_frequency": "weekly",
    },
    {
        "source_type": "instagram",
        "name": "What Kolkata Ate",
        "city": "Kolkata",
        "country": "India",
        "tier": None,
        "instagram_handle": "whatkolkataate",
        "website_url": None,
        "relevance_tags": ["kolkata", "food", "cafe", "reviews", "local"],
        "scrape_frequency": "weekly",
    },
    {
        "source_type": "instagram",
        "name": "Kolkata Food Walks",
        "city": "Kolkata",
        "country": "India",
        "tier": None,
        "instagram_handle": "kolkata_food_walks",
        "website_url": None,
        "relevance_tags": ["kolkata", "food", "street_food", "cafe", "local"],
        "scrape_frequency": "weekly",
    },
    # Indian coffee review accounts
    {
        "source_type": "instagram",
        "name": "Coffee Chronicles India",
        "city": None,
        "country": "India",
        "tier": None,
        "instagram_handle": "coffeechronicles.in",
        "website_url": None,
        "relevance_tags": ["india", "specialty_coffee", "reviews", "cafe"],
        "scrape_frequency": "weekly",
    },
    {
        "source_type": "instagram",
        "name": "The Coffee Brews Room",
        "city": None,
        "country": "India",
        "tier": None,
        "instagram_handle": "thecoffeebrewsroom",
        "website_url": None,
        "relevance_tags": ["india", "specialty_coffee", "brew_methods", "education"],
        "scrape_frequency": "weekly",
    },
    {
        "source_type": "instagram",
        "name": "Specialty Coffee India",
        "city": None,
        "country": "India",
        "tier": None,
        "instagram_handle": "specialtycoffeeindia",
        "website_url": None,
        "relevance_tags": ["india", "specialty_coffee", "community", "reviews"],
        "scrape_frequency": "weekly",
    },
    # ------------------------------------------------------------------
    # RESEARCH & INDUSTRY ORGANIZATIONS (15)
    # ------------------------------------------------------------------
    {
        "source_type": "research",
        "name": "Specialty Coffee Association (SCA)",
        "city": None,
        "country": "USA",
        "tier": None,
        "website_url": "https://sca.coffee",
        "relevance_tags": ["research", "standards", "certification", "industry_body"],
        "scrape_frequency": "monthly",
    },
    {
        "source_type": "research",
        "name": "Coffee Quality Institute (CQI)",
        "city": None,
        "country": "USA",
        "tier": None,
        "website_url": "https://www.coffeeinstitute.org",
        "relevance_tags": ["research", "quality", "certification", "q_grader"],
        "scrape_frequency": "monthly",
    },
    {
        "source_type": "research",
        "name": "World Coffee Research",
        "city": None,
        "country": "USA",
        "tier": None,
        "website_url": "https://worldcoffeeresearch.org",
        "relevance_tags": ["research", "agronomy", "climate", "genetics", "supply_chain"],
        "scrape_frequency": "monthly",
    },
    {
        "source_type": "research",
        "name": "National Restaurant Association of India (NRAI)",
        "city": "New Delhi",
        "country": "India",
        "tier": None,
        "website_url": "https://www.nrai.org",
        "relevance_tags": ["india", "restaurant_industry", "policy", "standards"],
        "scrape_frequency": "monthly",
    },
    {
        "source_type": "research",
        "name": "FSSAI (Food Safety and Standards Authority of India)",
        "city": "New Delhi",
        "country": "India",
        "tier": None,
        "website_url": "https://www.fssai.gov.in",
        "relevance_tags": ["india", "food_safety", "regulations", "standards"],
        "scrape_frequency": "monthly",
    },
    {
        "source_type": "research",
        "name": "International Coffee Organization (ICO)",
        "city": "London",
        "country": "UK",
        "tier": None,
        "website_url": "https://www.ico.org",
        "relevance_tags": ["research", "market_data", "supply_chain", "global_coffee"],
        "scrape_frequency": "monthly",
    },
    {
        "source_type": "research",
        "name": "Coffee Board of India",
        "city": "Bangalore",
        "country": "India",
        "tier": None,
        "website_url": "https://www.indiacoffee.org",
        "relevance_tags": ["india", "coffee_production", "research", "market_data"],
        "scrape_frequency": "monthly",
    },
    {
        "source_type": "research",
        "name": "Indian Institute of Plantation Management",
        "city": "Bangalore",
        "country": "India",
        "tier": None,
        "website_url": "https://www.iipmb.edu.in",
        "relevance_tags": ["india", "plantation", "research", "education"],
        "scrape_frequency": "monthly",
    },
    {
        "source_type": "research",
        "name": "India Coffee Trust",
        "city": None,
        "country": "India",
        "tier": None,
        "website_url": "https://www.indiacoffeetrust.org",
        "relevance_tags": ["india", "specialty_coffee", "research", "origin"],
        "scrape_frequency": "monthly",
    },
    {
        "source_type": "research",
        "name": "ICTA (Indian Coffee Traders Association)",
        "city": None,
        "country": "India",
        "tier": None,
        "website_url": "https://www.icta.in",
        "relevance_tags": ["india", "coffee_trade", "industry_body", "market_data"],
        "scrape_frequency": "monthly",
    },
    {
        "source_type": "research",
        "name": "Cafe Coffee Day Foundation",
        "city": "Bangalore",
        "country": "India",
        "tier": None,
        "website_url": "https://www.cafecoffeeday.com",
        "relevance_tags": ["india", "coffee_industry", "growers", "sustainability"],
        "scrape_frequency": "monthly",
    },
    {
        "source_type": "research",
        "name": "Alliance for Coffee Excellence",
        "city": None,
        "country": "USA",
        "tier": None,
        "website_url": "https://www.allianceforcoffeeexcellence.org",
        "relevance_tags": ["research", "cup_of_excellence", "quality", "origin"],
        "scrape_frequency": "monthly",
    },
    {
        "source_type": "research",
        "name": "Cup of Excellence",
        "city": None,
        "country": "USA",
        "tier": None,
        "website_url": "https://cupofexcellence.org",
        "relevance_tags": ["competition", "quality", "origin", "specialty_coffee"],
        "scrape_frequency": "monthly",
    },
    {
        "source_type": "research",
        "name": "Coffee Science Foundation",
        "city": None,
        "country": "USA",
        "tier": None,
        "website_url": "https://www.coffeesciencefoundation.org",
        "relevance_tags": ["research", "science", "brewing", "education"],
        "scrape_frequency": "monthly",
    },
    {
        "source_type": "research",
        "name": "World Barista Championship",
        "city": None,
        "country": None,
        "tier": None,
        "website_url": "https://worldbaristachampionship.org",
        "relevance_tags": ["competition", "barista", "specialty_coffee", "standards"],
        "scrape_frequency": "monthly",
    },
    # ------------------------------------------------------------------
    # BLOGS & YOUTUBE (10)
    # ------------------------------------------------------------------
    {
        "source_type": "publication",
        "name": "James Hoffmann YouTube",
        "city": "London",
        "country": "UK",
        "tier": None,
        "website_url": "https://www.youtube.com/@jameshoffmann",
        "rss_url": None,
        "instagram_handle": "jimseven",
        "relevance_tags": ["video", "coffee_education", "reviews", "equipment"],
        "scrape_frequency": "weekly",
    },
    {
        "source_type": "publication",
        "name": "Lance Hedrick YouTube",
        "city": None,
        "country": "USA",
        "tier": None,
        "website_url": "https://www.youtube.com/@LanceHedrick",
        "rss_url": None,
        "instagram_handle": "lance.hedrick",
        "relevance_tags": ["video", "espresso", "equipment", "dialing_in"],
        "scrape_frequency": "weekly",
    },
    {
        "source_type": "publication",
        "name": "European Coffee Trip YouTube",
        "city": "Prague",
        "country": "Czech Republic",
        "tier": None,
        "website_url": "https://www.youtube.com/@EuropeanCoffeeTrip",
        "rss_url": None,
        "instagram_handle": "europeancoffeetrip",
        "relevance_tags": ["video", "cafe_reviews", "specialty_coffee", "travel"],
        "scrape_frequency": "weekly",
    },
    {
        "source_type": "publication",
        "name": "Sprometheus YouTube",
        "city": None,
        "country": "USA",
        "tier": None,
        "website_url": "https://www.youtube.com/@Sprometheus",
        "rss_url": None,
        "instagram_handle": "the_real_sprometheus",
        "relevance_tags": ["video", "espresso", "equipment_reviews", "specialty_coffee"],
        "scrape_frequency": "weekly",
    },
    {
        "source_type": "publication",
        "name": "The Coffee Chronicler",
        "city": None,
        "country": "Denmark",
        "tier": None,
        "website_url": "https://thecoffeechronicler.com",
        "rss_url": "https://thecoffeechronicler.com/feed",
        "instagram_handle": "coffeechronicler",
        "relevance_tags": ["blog", "origin", "tasting_notes", "specialty_coffee"],
        "scrape_frequency": "weekly",
    },
    {
        "source_type": "publication",
        "name": "Home-Barista.com",
        "city": None,
        "country": "USA",
        "tier": None,
        "website_url": "https://home-barista.com",
        "rss_url": "https://home-barista.com/feed",
        "instagram_handle": None,
        "relevance_tags": ["forum", "espresso", "equipment", "home_barista"],
        "scrape_frequency": "weekly",
    },
    {
        "source_type": "publication",
        "name": "CoffeeGeek.com",
        "city": None,
        "country": "Canada",
        "tier": None,
        "website_url": "https://coffeegeek.com",
        "rss_url": "https://coffeegeek.com/feed",
        "instagram_handle": "coffeegeek",
        "relevance_tags": ["forum", "equipment_reviews", "espresso", "home_barista"],
        "scrape_frequency": "weekly",
    },
    {
        "source_type": "publication",
        "name": "I Need Coffee",
        "city": None,
        "country": "Australia",
        "tier": None,
        "website_url": "https://ineedcoffee.com",
        "rss_url": "https://ineedcoffee.com/feed",
        "instagram_handle": "ineedcoffeecom",
        "relevance_tags": ["blog", "brew_methods", "education", "recipes"],
        "scrape_frequency": "weekly",
    },
    {
        "source_type": "publication",
        "name": "Clive Coffee Blog",
        "city": "Portland",
        "country": "USA",
        "tier": None,
        "website_url": "https://clivecoffee.com/blogs/learn",
        "rss_url": None,
        "instagram_handle": "clivecoffee",
        "relevance_tags": ["blog", "equipment", "espresso", "education"],
        "scrape_frequency": "weekly",
    },
    {
        "source_type": "publication",
        "name": "Prima Coffee Blog",
        "city": None,
        "country": "USA",
        "tier": None,
        "website_url": "https://prima-coffee.com/learn",
        "rss_url": "https://prima-coffee.com/blog.atom",
        "instagram_handle": "primacoffeeequip",
        "relevance_tags": ["blog", "equipment", "brew_methods", "education"],
        "scrape_frequency": "weekly",
    },
]

# Sanity check — must have 80+ entries
assert len(CONTENT_SOURCES) >= 80, (
    f"Expected 80+ CONTENT_SOURCES entries, got {len(CONTENT_SOURCES)}"
)
